import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/providers/themeProvider';
import React from 'react';
import { Header } from '@/components/header';
import { Noto_Sans } from 'next/font/google';

const roboto = Noto_Sans({
  weight: '500',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider>
          <Header />
          <main className='mt-3 px-layout'>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
