import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/providers/themeProvider';
import React from 'react';
import { Header } from '@/components/header';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/services/i18n/routing';

import { Noto_Sans } from 'next/font/google';
import { HttpClientProvider } from '@/providers/httpClientProvider';
import { SnackbarProvider } from '@/providers/snackbarProvider';
import { StoreProvider } from '@/providers/storeProvider';

const roboto = Noto_Sans({
  weight: '500',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={`${roboto.className} antialiased`}>
        <StoreProvider>
          <ThemeProvider>
            <NextIntlClientProvider>
              <SnackbarProvider>
                <HttpClientProvider>
                  <Header />
                  <main className='mt-3 px-layout'>{children}</main>
                </HttpClientProvider>
              </SnackbarProvider>
            </NextIntlClientProvider>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
